version: '3.8'

services:
  backend:
    build:
      context: ../src/backend
      dockerfile: Startup/Dockerfile
    ports:
      - "5000:80"
    networks:
      - mynetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  mynetwork:
    driver: bridge
  
  #frontend:
  #  build:
  #    context: ../src/frontend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3000:3000"
