name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: full-stack-project-blueprint
  REPO_URL: git@github.com:username/repo.git

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy
      run: |
        ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP_ADDRESS }} << 'ENDSSH'
          sudo mkdir -p /srv/${{ env.PROJECT_NAME }}
          cd /srv/${{ env.PROJECT_NAME }}
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          git clone ${{ env.REPO_URL }}
          docker-compose -f /srv/${{ env.PROJECT_NAME }}/deploy/docker-compose.yml down
          docker-compose -f /srv/${{ env.PROJECT_NAME }}/deploy/docker-compose.yml up -d --build
        ENDSSH
