name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  REPO_URL: ${{ secrets.REPO_URL }} # Add this line, assuming you have set a REPO_URL in your GitHub secrets

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key to known_hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "${{ secrets.VM_IP_ADDRESS }} $(ssh-keyscan -H ${{ secrets.VM_IP_ADDRESS }})" >> ~/.ssh/known_hosts

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH and Deploy
      run: |
        ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP_ADDRESS }} << 'ENDSSH'
          if [ ! -d "/srv/${PROJECT_NAME}" ]; then
            git clone ${REPO_URL} /srv/${PROJECT_NAME}
          fi
          cd /srv/${PROJECT_NAME}
          git pull origin main
          docker-compose -f /srv/${PROJECT_NAME}/deploy/docker-compose.yml down
          docker-compose -f /srv/${PROJECT_NAME}/deploy/docker-compose.yml up -d --build
        ENDSSH
