name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Key to known_hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.VM_IP_ADDRESS }} >> ~/.ssh/known_hosts

    - name: SSH and Deploy
      run: |
        ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP_ADDRESS }} << 'ENDSSH'
          VM_PATH="/srv/full-stack-project-blueprint"
          sudo mkdir -p ${VM_PATH}  # Use sudo to ensure permission
          cd ${VM_PATH} || exit 1   # Exit if cd fails
          if [ -d "repo" ]; then
            cd repo && git pull origin main
          else
            git clone https://github.com/georgy-kirilov/full-stack-project-blueprint.git repo
          fi
          docker-compose -f ${VM_PATH}/deploy/docker-compose.yml down || true
          docker-compose -f ${VM_PATH}/deploy/docker-compose.yml up -d --build
        ENDSSH
